### ISSUE TITLE
wrong date on 2016-17/it.1.json

### ISSUE THREAD

**Issue by abfede** [opendatajson/football.json#17]
Hello there!
I noticed that matches on 2016-17/it.1.json from line 393 to 453 have this "date": "2016-12-15".
If these are the scores of these matches, I will bet on them :D

**Comment by geraldb** [comment]
@abfede  Good luck. Please send questions and comments for discussion to the [forum / mailing list](http://groups.google.com/group/opensport). Thanks. Cheers.
