### ISSUE TITLE
Python robot

### ISSUE THREAD

**Issue by enadol** [opendatajson/football.json#18]
Greetings! I started coding the following python robot to read the .txt files (for instance, "1-bundesliga-i.txt)" and generate an emulated version of the JSONs featured in football.json by @geraldb 

https://github.com/enadol/fbjsonrobot

Just make sure the proper .txt file is on the same folder, launch the file launch.py and that's (almost) it! For other leagues, adapt is required.

It's still not perfect, but that's Github is for! 😄 

Have fun! ⚽️ ⚽️

**Comment by geraldb** [comment]
Great. Thanks for sharing. Keep it up. Prosit 2017! Cheers.

**Comment by geraldb** [comment]
For your information: Added your comments to the readme, see <https://github.com/opendatajson/football.json#more> Keep it up. Cheers.
